In [1]:
import numpy
import pandas
import sklearn
import matplotlib

print("all good")

all good


In [3]:
model_name = "logistic-regression"                         # str: text, wrapped in quotes
print(model_name, type(model_name))

logistic-regression <class 'str'>


In [ ]:
epoch = 12                  # int: a whole number, no decimal
print(epoch, type(epoch))

12 <class 'int'>


In [ ]:
accuracy = 0.87             # float: a number with a decimal point
print(accuracy, type(accuracy))

0.87 <class 'float'>


In [6]:
converged = True                    # bool: only ever True or False
print(converged, type(converged))

True <class 'bool'>


In [7]:
best_model = None                   # None: represents "no value yet" — nothing assigned
print(best_model, type(best_model))

None <class 'NoneType'>


In [8]:
accuracy_str = "0.874"
accuracy_float = float(accuracy_str)      # converts text into an actual number Python can do math with
print(accuracy_float, type(accuracy_float))

0.874 <class 'float'>


In [10]:
some_float = 12.9
some_int = int(some_float)     #  .9 is dropped, not rounded, so 12.9 becomes 12,truncates the decimal 
print(some_int, type(some_int))

12 <class 'int'>


In [13]:
model_name = "logistic-regression-v1"
accuracy = 0.874
epoch = 12

print(f"the model used is {model_name} with accuracy of {accuracy:.1%} and {epoch} epoch count ")
# :f tell python that the string contain variables in {} that we have to replace with their values
# :.1% formats the float as a percentage with 1 decimal place (0.874 -> 87.4%)

the model used is logistic-regression-v1 with accuracy of 87.4% and 12 epoch count 


In [27]:
accuracy, latency=0.90,250
res=""
if accuracy >=0.87 and latency >=230:
        res= "ship it"
elif accuracy < 0.70 :
        res= "too slow"
else:
        res= "keep training"
print(f"{res}")

ship it


In [33]:
scores = [0.62, 0.71, 0.79, 0.85]

for epoch, score in enumerate(scores):
    print(f" epoch {epoch}: {score}" )   # build an f-string here: "epoch {epoch}: {score}"

 epoch 0: 0.62
 epoch 1: 0.71
 epoch 2: 0.79
 epoch 3: 0.85


In [34]:
# List: useful when we need an ordered collection that can be changed
scores = [65, 70, 80, 90]

# Tuple: useful for fixed data that should not be changed
student_info = ("Yvette", 22, "AI")

# Dictionary: useful for storing data as key-value pairs
student = {
    "name": "Yvette",
    "age": 22,
    "score": 85
}

# Set: useful when we need unique values and don't want duplicates
unique_scores = {65, 70, 80, 90, 90}

print(scores)
print(student_info)
print(student)
print(unique_scores)

[65, 70, 80, 90]
('Yvette', 22, 'AI')
{'name': 'Yvette', 'age': 22, 'score': 85}
{80, 65, 90, 70}


In [38]:
scores = [45, 60, 72, 85, 90]

# Keep only scores that are  higher than 70 
passing_scores = [score for score in scores if score > 70]

print(passing_scores)

[72, 85, 90]


In [39]:
def normalise(values, minimum=None, maximum=None):
    """
    Scale a list of numbers to the 0-1 range.

    Args:
        values: List of numbers to normalise.
        minimum: Optional minimum bound.
        maximum: Optional maximum bound.

    Returns:
        A list of normalised values.
    """

In [43]:
def normalise(values, minimum=None, maximum=None):
    """
    Scale a list of numbers to the 0-1 range.

    Args:
        values: List of numbers to normalise.
        minimum: Optional minimum bound.
        maximum: Optional maximum bound.

    Returns:
        A list of normalised values.
    """

    if minimum is None:
        minimum = min(values)

    if maximum is None:
        maximum = max(values)

    if minimum == maximum:
        return [0.0 for value in values]

    return [(value - minimum) / (maximum - minimum) for value in values]

In [44]:
print(normalise([10, 20, 30, 40]))

[0.0, 0.3333333333333333, 0.6666666666666666, 1.0]


In [45]:
print(normalise([5, 5, 5, 5]))

[0.0, 0.0, 0.0, 0.0]


In [4]:
def summarise_scores(scores):
    """
    Calculate basic statistics for a list of scores.

    Args:
        scores: List of numerical scores.

    Returns:
        A dictionary containing count, mean, minimum, maximum,
        and the number of scores greater than or equal to 0.8.
    """

    if not scores:
        return {
            "count": 0,
            "mean": None,
            "minimum": None,
            "maximum": None,
            "above_threshold": 0
        }

    return {
        "count": len(scores),
        "mean": sum(scores) / len(scores),
        "minimum": min(scores),
        "maximum": max(scores),
        "above_threshold": sum(1 for score in scores if score >= 0.8)
    }

In [7]:
print(summarise_scores([0.5, 0.75, 0.8, 0.9, 0.95]))

{'count': 5, 'mean': 0.78, 'minimum': 0.5, 'maximum': 0.95, 'above_threshold': 3}


In [6]:
print(summarise_scores([]))

{'count': 0, 'mean': None, 'minimum': None, 'maximum': None, 'above_threshold': 0}


In [8]:
def safe_divide(a, b):
    """
    Safely divide a by b.

    Args:
        a: The numerator.
        b: The denominator.

    Returns:
        The result of a / b, or None if b is zero.
    """
    
    if b == 0:
        return None

    return a / b

In [9]:
print(safe_divide(10, 2))
print(safe_divide(10, 0))

5.0
None


In [14]:
import numpy as np

scores = np.array([10, 20, 30, 40, 50, 60])

print("Mean:", scores.mean())
print("Standard deviation:", scores.std())
print("Minimum:", scores.min())
print("Maximum:", scores.max())

Mean: 35.0
Standard deviation: 17.07825127659933
Minimum: 10
Maximum: 60


In [15]:
data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("Shape:", data.shape)
print("Transpose shape:", data.T.shape)

Shape: (3, 4)
Transpose shape: (4, 3)


In [16]:
column_means = data.mean(axis=0)

print("Column means:", column_means)

Column means: [50. 60. 70. 80.]


In [17]:
centered = data - column_means

print("Centered array:")
print(centered)

Centered array:
[[-40. -40. -40. -40.]
 [  0.   0.   0.   0.]
 [ 40.  40.  40.  40.]]


In [18]:
import numpy as np

# 1. 1-D array and statistics
scores = np.array([10, 20, 30, 40, 50, 60])

print("Mean:", scores.mean())
print("Standard deviation:", scores.std())
print("Minimum:", scores.min())
print("Maximum:", scores.max())


# 2. 2-D array and shapes
data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("\nShape:", data.shape)
print("Transpose shape:", data.T.shape)


# 3. Subtract column means using broadcasting
column_means = data.mean(axis=0)

print("\nColumn means:", column_means)

centered = data - column_means

print("Centered array:")
print(centered)

Mean: 35.0
Standard deviation: 17.07825127659933
Minimum: 10
Maximum: 60

Shape: (3, 4)
Transpose shape: (4, 3)

Column means: [50. 60. 70. 80.]
Centered array:
[[-40. -40. -40. -40.]
 [  0.   0.   0.   0.]
 [ 40.  40.  40.  40.]]


In [19]:
import pandas as pd

students = {
    "name": ["Alice", "Brian", "Clara", "David", "Eva", "Frank"],
    "age": [20, 21, 19, 22, 20, 21],
    "score": [0.85, 0.72, 0.91, 0.65, 0.88, 0.76],
    "city": ["Kigali", "Musanze", "Kigali", "Huye", "Rubavu", "Kigali"],
    "study_hours": [5, 3, 6, None, 5, 4]
}

df = pd.DataFrame(students)

print(df)

    name  age  score     city  study_hours
0  Alice   20   0.85   Kigali          5.0
1  Brian   21   0.72  Musanze          3.0
2  Clara   19   0.91   Kigali          6.0
3  David   22   0.65     Huye          NaN
4    Eva   20   0.88   Rubavu          5.0
5  Frank   21   0.76   Kigali          4.0
